# Generated by Django 3.1 on 2020-08-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergitlabaccesstoken",
            name="user_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
