# Generated by Django 3.1 on 2020-08-29 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_usergitlaboauthtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="gitlabrepochmapping",
            name="gitlab_oauth_token",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.usergitlaboauthtoken",
            ),
            preserve_default=False,
        ),
    ]
