# Generated by Django 3.1 on 2020-08-29 20:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_gitlabrepochmapping_gitlab_oauth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitlabrepochmapping',
            name='webhook_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='gitlabrepochmapping',
            name='webhook_secret',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
